version: '{build}'
branches:
  only:
  - master
  - appveyor
  - /^maint.*/
environment:
  GITTEST_INVASIVE_FS_STRUCTURE: 1
  GITTEST_INVASIVE_FS_SIZE: 1

  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    CMAKE_OPTIONS: -G"MinGW Makefiles"
    ARCH: x86
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    CMAKE_OPTIONS: -G"MinGW Makefiles"
    ARCH: amd64

install:
- set PATH=%TEMP%\mingw64\bin;%TEMP%\mingw32\bin;%PATH%
- ps: |
    mkdir build
    cd build
    if ($env:GENERATOR -eq "MinGW Makefiles") {
      ../ci/setup-mingw.ps1
      dir $env:TEMP
      dir ${env:TEMP}\mingw64
      dir ${env:TEMP}\mingw64\bin
      dir ${env:TEMP}\mingw32
      dir ${env:TEMP}\mingw32\bin
    }

build_script:
- ps: |
    ../ci/build.ps1

test_script:
- ps: |
    ../ci/test.ps1
