version: '{build}'
branches:
  only:
  - master
  - appveyor
  - /^maint.*/
environment:
  GITTEST_INVASIVE_FS_STRUCTURE: 1
  GITTEST_INVASIVE_FS_SIZE: 1

  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    CMAKE_OPTIONS: -G"MinGW Makefiles"
    ARCH: x86
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    CMAKE_OPTIONS: -G"MinGW Makefiles"
    ARCH: amd64

install:
- set PATH=%TEMP%\mingw64;%TEMP%\mingw32;%PATH%
- ps: |
    mkdir build
    cd build
    if ($env:GENERATOR -eq "MinGW Makefiles") {
      ../ci/setup-mingw.ps1
      dir %TEMP%
      dir %TEMP%\mingw64
      dir %TEMP%\mingw32
    }

build_script:
- ps: |
    ../ci/build.ps1

test_script:
- ps: |
    ../ci/test.ps1
